repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            node_modules/.*|
            \.angular/.*|
            \.venv/.*|
            dist/.*|
            .*\.lock$
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            node_modules/.*|
            \.angular/.*|
            \.venv/.*|
            dist/.*|
            .*\.lock$
          )$
      - id: check-yaml
        files: \.pre-commit-config\.yaml$
      - id: check-json
        files: (package\.json|angular\.json)$
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        files: ^(src/python_placeholder/|tests/).*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(src/python_placeholder/|tests/).*\.py$
